default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false

development:
  <<: *default
  database: ec_app
  username: webapp
  password: webapp
  host: localhost

production:
  <<: *default
  database: ec_app
  username: webapp
  password: webapp
  host: localhost